version: '3.2'
services:
  web:
      container_name: web
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./static:/usr/share/nginx/html
      depends_on:
        - app

  app:
    build:
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    expose:
      - 8000
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./static/images:/app/static/images

  db:
    image: postgres:15
    command: ["postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=my_log"]
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=twitter_clone_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
