version: '3.2'
services:
  web:
    container_name: web
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    expose:
      - 8000
    container_name: src
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./dist/images:/app/dist/images

  db:
    image: postgres:15-alpine
    command: [ "postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=my_log" ]
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=twitter_clone_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
