version: '3.2'
services:
  web:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    expose:
      - 8000
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./dist/images:/app/dist/images

  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data
