"""Added indexes

Revision ID: 4bfd6a2ce1b9
Revises: c197413c7792
Create Date: 2023-10-22 18:42:14.094364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfd6a2ce1b9'
down_revision: Union[str, None] = 'c197413c7792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_followers_followed_id'), 'followers', ['followed_id'], unique=False)
    op.create_index(op.f('ix_followers_follower_id'), 'followers', ['follower_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_likes_tweet_id'), 'likes', ['tweet_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_tweets_tweet_id'), 'tweets', ['tweet_id'], unique=False)
    op.create_index(op.f('ix_tweets_user_id'), 'tweets', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tweets_user_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_tweet_id'), table_name='tweets')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_tweet_id'), table_name='likes')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_followers_follower_id'), table_name='followers')
    op.drop_index(op.f('ix_followers_followed_id'), table_name='followers')
    # ### end Alembic commands ###
